version: '3.8'

services:
  postgres-user:
    container_name: postgres-user
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: radman
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    ports:
      - "5431:5431"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U radman -d user-service -p 5431"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: postgres -p 5431
    restart: unless-stopped

volumes:
  postgres-user-data: